# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['prometheus:9090']
#  - job_name: 'node'
#
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

#    scrape_interval: 5s
#
#    static_configs:
    - targets: ['localhost:9100']
  - job_name: 'spark-master-applications'

    metrics_path: '/metrics/applications/prometheus'
    static_configs:
    - targets: ['spark-master:8080']

  - job_name: 'spark-master'

    metrics_path: '/metrics/master/prometheus'
    static_configs:
    - targets: ['spark-master:8080']

  - job_name: 'spark-workers'

    metrics_path: '/metrics/prometheus'
    static_configs:
    - targets: ['spark-worker_1:8081', 'spark-worker_2:8081']

  - job_name: 'spark-executors'

    scrape_interval: 1s
    metrics_path: '/metrics/executors/prometheus'

    static_configs:
    - targets: ['spark-worker_1:4040', 'spark-worker_1:4041', 'spark-worker_1:4042', 'spark-worker_2:4040', 'spark-worker_2:4041', 'spark-worker_2:4042']

  - job_name: 'spark-drivers'

    scrape_interval: 1s
    metrics_path: '/metrics/prometheus'

    static_configs:
    - targets: ['spark-worker_1:4040', 'spark-worker_1:4041', 'spark-worker_1:4042', 'spark-worker_2:4040', 'spark-worker_2:4041', 'spark-worker_2:4042']
