{
 "title": "AWS EC2 Spark Cluster Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "query": { "query": "label_values(application_id)" } }
  ]
 },
 "panels": [
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Used Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_worker_coresUsed_Number)"
    }
   ]
  },
  {
   "title": "Total Free Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_worker_coresFree_Number)"
    }
   ]
  },
  {
   "title": "Total Used Memory (MB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_worker_memUsed_MB_Number) / 1000"
    }
   ]
  },
  {
   "title": "Total Free Memory (MB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_worker_memFree_MB_Number)/1000"
    }
   ]
  },
  { "title": "Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "No. of Executors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(metrics_worker_executors_Number)"
    }
   ]
  },
  {
   "title": "Total Tasks per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(metrics_executor_totalTasks_total {executor_id =~ \"[0-9]*\", application_id = \"$application\"}[1m])",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Allocation Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "metrics_spark_driver_ExecutorAllocationManager_executors_numberAllExecutors_Value / metrics_spark_driver_ExecutorAllocationManager_executors_numberTargetExecutors_Value",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed vs Completed Tasks",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(metrics_executor_failedTasks_total / metrics_executor_completedTasks_total {application_id =~\"$application\", executor_id =~\"[0-9]*\"}) * 100"
    }
   ]
  },
  {
   "title": "GCTime vs TotalDuration",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(metrics_executor_totalGCTime_seconds_total / metrics_executor_totalDuration_seconds_total {application_id =~\"$application\", executor_id =~\"[0-9]*\"}) * 100"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_application_Spark_Pi_1626108338804_runtime_ms_Number * 1000"
    }
   ]
  },
  {
   "title": "MemoryUsed (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "(metrics_executor_memoryUsed_bytes {application_id =~\"$application\"})  / 1048576",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "OnHeap + OffHeap + DirectPool (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "(metrics_executor_DirectPoolMemory_bytes + metrics_executor_JVMHeapMemory_bytes + metrics_executor_DirectPoolMemory_bytes {application_id =~\"$application\"} ) / 1048576",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Shuffle Read (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "metrics_executor_totalShuffleRead_bytes_total {application_id =~\"$application\", executor_id =~ \"[0-9]*\"} / 1048576",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Shuffle Write Data (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "metrics_executor_totalShuffleWrite_bytes_total {application_id =~ \"$application\", executor_id =~ \"[0-9*]\"} / 1048576",
     "legendFormat": "{{executor_id}}"
    }
   ]
  }
 ]
}